
default: &default
  adapter: postgresql

  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template1
development:
  <<: *default
  database: kadaifb_development

test:
  <<: *default
  database: kadaifb_test

production:
  <<: *default
  database: kadaifb_production
  username: kadaifb
  password: <%= ENV['KADAIFB_DATABASE_PASSWORD'] %>
