# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1cd9923f1bd6bac5e9b5eed9970067df1d70077095faf6a5d43423b5eddd11117ba320ed6e8069585cbffb7bec86ff99e2d563213822bf2fe3f8df05c63e8e3c

test:
  secret_key_base: 2b1411995837d0ee325bd49a6c02441ee718bc7f4bc0233bf5d46c219e1da76e43e3d3f9a9c749b5a9b73d424cf7641166ee3df39015f91437503225e989d081

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
